all:
  children:
    uat:
      hosts:
        uat-server:
          ansible_host: 192.168.0.183
          ansible_user: deploy
          ansible_ssh_private_key_file: /var/lib/jenkins/.ssh/id_ed25519