---
# Application
app_name: localgov_aroroy

# Docker
docker_container_name: localgov_aroroy
docker_image_repo: tondosolutions/localgov_aroroy
docker_image_tag: latest
docker_network: tondo_network
docker_ports: 
  - "3013:3000"

# Container
docker_restart_policy: unless-stopped