---
- name: Run application container
  community.docker.docker_container:
    name: "{{ docker_container_name }}"
    recreate: true

    image: "{{ docker_image }}"
    ports: "{{ docker_ports }}"
    state: started

    volumes:
      - "{{ app_directory }}:/app"
    
    networks:
      - name: "{{ docker_network }}"
    
    restart_policy: "{{ docker_restart_policy }}"
    command: "{{ docker_container_command }}"