---
- name: Check running container
  ansible.builtin.command:
    cmd: docker ps --filter "name={{ docker_container_name }}" 

  register: docker_ps

- name: Display running containers
  ansible.builtin.debug:
    var: docker_ps.stdout_lines